/*
 * Script de Inicialización de Base de Datos - Pet Health Tracker
 * Versión: 1.0
 * Motor: PostgreSQL
 * Estructura: ID -> FKs -> Datos -> Auditoría
 */

-- ========================================================
-- 1. LIMPIEZA PREVIA (Eliminar tablas existentes)
-- ========================================================
DROP TABLE IF EXISTS public.veterinary_visits CASCADE;
DROP TABLE IF EXISTS public.deworming_treatments CASCADE;
DROP TABLE IF EXISTS public.vaccinations CASCADE;
DROP TABLE IF EXISTS public.feeding_schedule CASCADE;
DROP TABLE IF EXISTS public.reminders CASCADE;
DROP TABLE IF EXISTS public.pets CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ========================================================
-- 2. TABLA: USERS
-- ========================================================
CREATE TABLE public.users (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Datos Principales
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(120) NOT NULL,
    phone VARCHAR(20),
    profile_picture_url VARCHAR(255),
    
    -- Seguridad y Estado
    email_verified BOOLEAN DEFAULT FALSE,
    reset_password_token VARCHAR(255),
    reset_token_expires TIMESTAMP(6),

    -- Auditoría (BaseEntity)
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),

    -- Restricciones
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ========================================================
-- 3. TABLA: PETS
-- ========================================================
CREATE TABLE public.pets (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relaciones
    user_id BIGINT NOT NULL,

    -- Datos de la Mascota
    name VARCHAR(100) NOT NULL,
    species VARCHAR(255) NOT NULL,
    breed VARCHAR(100),
    color VARCHAR(100),
    gender VARCHAR(255),
    date_of_birth DATE,
    age_years INTEGER,
    age_months INTEGER,
    weight NUMERIC(5, 2),
    weight_unit VARCHAR(255),
    microchip_number VARCHAR(50),
    profile_picture_url VARCHAR(255),
    health_notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,

    -- Auditoría (BaseEntity)
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_pets_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT uq_pets_microchip UNIQUE (microchip_number),
    
    -- Validaciones (Checks)
    CONSTRAINT chk_pets_species CHECK (species IN ('DOG', 'CAT', 'BIRD', 'FISH', 'REPTILE', 'RABBIT', 'HAMSTER', 'OTHER')),
    CONSTRAINT chk_pets_gender CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT chk_pets_weight_unit CHECK (weight_unit IN ('KG', 'LB'))
);

-- ========================================================
-- 4. TABLA: REMINDERS
-- ========================================================
CREATE TABLE public.reminders (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relaciones
    user_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,

    -- Datos del Recordatorio
    title VARCHAR(100) NOT NULL,
    description TEXT,
    reminder_type VARCHAR(255) NOT NULL,
    
    -- Fecha y Hora
    due_date DATE,
    due_time TIME(6),
    
    -- Estado
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP(6),
    notification_sent BOOLEAN DEFAULT FALSE,

    -- Recurrencia
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_pattern VARCHAR(255),
    custom_recurrence JSON,

    -- Auditoría (BaseEntity)
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_reminders_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_reminders_pet FOREIGN KEY (pet_id) REFERENCES public.pets(id),

    -- Validaciones
    CONSTRAINT chk_reminders_type CHECK (reminder_type IN ('VACCINATION', 'DEWORMING', 'MEDICATION', 'APPOINTMENT', 'GROOMING', 'FEEDING', 'EXERCISE', 'OTHER')),
    CONSTRAINT chk_reminders_pattern CHECK (recurrence_pattern IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM'))
);

-- ========================================================
-- 5. TABLA: FEEDING_SCHEDULE
-- ========================================================
CREATE TABLE public.feeding_schedule (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relaciones
    pet_id BIGINT NOT NULL,

    -- Detalles de Alimentación
    food_type VARCHAR(255) NOT NULL,
    food_brand VARCHAR(255),
    portion_size NUMERIC(10, 2),
    portion_unit VARCHAR(10),
    feeding_frequency VARCHAR(20) NOT NULL,
    
    -- Configuración Avanzada
    custom_schedule JSONB,
    special_instructions TEXT,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,

    -- Auditoría (BaseEntity) - Nota: Tu dump original no tenía created_by/updated_by aquí, pero los agrego por consistencia si usas BaseEntity
    created_at TIMESTAMP(6), 
    updated_at TIMESTAMP(6),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_feeding_pet FOREIGN KEY (pet_id) REFERENCES public.pets(id),

    -- Validaciones
    CONSTRAINT chk_feeding_frequency CHECK (feeding_frequency IN ('DAILY_ONCE', 'DAILY_TWICE', 'DAILY_THRICE', 'CUSTOM')),
    CONSTRAINT chk_feeding_unit CHECK (portion_unit IN ('G', 'KG', 'CUP', 'ML', 'OZ'))
);

CREATE TABLE public.deworming_treatments (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación
    pet_id BIGINT NOT NULL,

    -- Datos del Tratamiento
    treatment_name VARCHAR(200) NOT NULL,
    administration_date DATE NOT NULL,
    next_due_date DATE,
    medication_type VARCHAR(50) NOT NULL, -- Sustituye ENUM
    dosage VARCHAR(100),
    veterinarian_name VARCHAR(200),
    notes TEXT,

    -- Auditoría
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_deworming_pet FOREIGN KEY (pet_id) REFERENCES public.pets(id) ON DELETE CASCADE,

    -- Validaciones (Sustituye ENUM)
    CONSTRAINT chk_deworming_med_type CHECK (medication_type IN ('tablet', 'liquid', 'spot_on', 'injection', 'other'))
);

CREATE TABLE public.vaccinations (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación
    pet_id BIGINT NOT NULL,

    -- Datos de la Vacuna
    vaccine_name VARCHAR(200) NOT NULL,
    vaccine_type VARCHAR(100),
    administration_date DATE NOT NULL,
    next_due_date DATE,
    batch_number VARCHAR(100),
    veterinarian_name VARCHAR(200),
    certificate_url VARCHAR(255),
    notes TEXT,

    -- Auditoría
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_vaccination_pet FOREIGN KEY (pet_id) REFERENCES public.pets(id) ON DELETE CASCADE
);

CREATE TABLE public.veterinary_visits (
    -- Identificador
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación
    pet_id BIGINT NOT NULL,

    -- Datos de la Visita
    visit_date DATE NOT NULL,
    visit_type VARCHAR(50) NOT NULL, -- Sustituye ENUM
    veterinarian_name VARCHAR(200),
    clinic_name VARCHAR(200),
    reason_for_visit TEXT,
    diagnosis TEXT,
    treatment_notes TEXT,
    prescribed_medications TEXT,
    cost NUMERIC(8,2), -- Utiliza NUMERIC para precisión monetaria
    next_visit_date DATE,
    attachments_urls JSONB, -- JSONB es la práctica común en PostgreSQL

    -- Auditoría
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    -- Restricciones y Claves Foráneas
    CONSTRAINT fk_visits_pet FOREIGN KEY (pet_id) REFERENCES public.pets(id) ON DELETE CASCADE,

    -- Validaciones (Sustituye ENUM)
    CONSTRAINT chk_visit_type CHECK (visit_type IN ('routine_checkup', 'emergency', 'vaccination', 'surgery', 'dental', 'other'))
);