import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  name: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  sectionImage: {
    alignItems: "center",
    marginTop: 20,
    paddingHorizontal: 16,
  },
  profileImage: {
    width: 150,
    height: 150,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ea9b56",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  nameImage: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#ea9b56",
    marginTop: 10,
  },
  sectionInfo: {
    marginTop: 30,
    backgroundColor: "#F7F7F6",
    padding: 20,
    marginHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#628141",
  },
  infoItem: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    color: "#ea9b56",
    marginBottom: 4,
    fontWeight: "500",
    marginLeft: 0,
  },
  value: {
    fontSize: 16,
    color: "#333",
    fontWeight: "400",
    marginLeft: 0,
  },
  sectionPets: {
    marginTop: 30,
    backgroundColor: "#F7F7F6",
    padding: 20,
    marginHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#628141",
  },
  textPets: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 20,
    marginLeft: 0,
  },
  petsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    flexWrap: "wrap",
    minHeight: 120, // Altura mínima para mantener el diseño
  },
  petItem: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  addPetItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  profilePets: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#ea9b56",
    marginBottom: 8,
  },
  namePets: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#ea9b56",
    textAlign: "center",
  },
  addPets: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#628141",
    borderStyle: "dotted",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: "#cce0bcff",
  },
  addPetText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#628141",
    textAlign: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f1d9b4ff",
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: "#ea9b56",
    fontWeight: "500",
  },
});